### PR TITLE
Fixes drag n drop images to upload. Adds copy/paste image upload.

### PR DESCRIPTION
**Pull request by ermacaz**
Uploading images by dragging files to the message textarea has been broken in chrome due to chrome adding stricter CORS prevention at some point.  These changes allow the uploading to be done by transloader.js in the background avoiding a CORS issue.  This also enables resizing images uploaded this way if resizing is enabled.  
I also added some copy/paste image functionality.  It seems to work if you copy form a webpage or discord, but not an image file on your computer.

### CODE REVIEW

**Comment by Seiru** [comment]
Just wanna point out that drag and dropping images from another Chrome window/tab doesn't seem to work. Not sure if that ever worked in the original though. If that's fine, I can merge this.

**Comment by ermacaz** [comment]
ah, never even thought to try that; was just dragging image files from desktop.  I will look into it tomorrow and see if I can get it working.

**Comment by ermacaz** [comment]
ok that should do it.
I dont think there's anything else I was planning to do unless someone requests something I take an interest in so feel free to publish - I dont think I will have anymore pull requests for a while.  
I did want to try and add gif resizing but it looks like a pain in the ass so that probably wont happen anytime soon if at all

**Comment by Seiru** [comment]
This looks good to me if you're ready to merge.

**Comment by ermacaz** [comment]
Ya its good to go from my end.

**Pull request merged**
